apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
  namespace: three-tier-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
      - name: api-2
        image: api-2:latest
        imagePullPolicy: Never  # For local minikube development
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: AZURE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AZURE_CONTAINER_NAME
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-2-service
  namespace: three-tier-demo
spec:
  selector:
    app: api-2
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP
