apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1
  namespace: three-tier-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-1
  template:
    metadata:
      labels:
        app: api-1
    spec:
      containers:
      - name: api-1
        image: api-1:latest
        imagePullPolicy: Never  # For local minikube development
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: SQL_SERVER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SQL_SERVER
        - name: SQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SQL_DATABASE
        - name: SQL_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SQL_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-1-service
  namespace: three-tier-demo
spec:
  selector:
    app: api-1
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
